name: Publication

on:
  push:
    branches: [ main ]

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup Scripts 🧩
        run: |
          pip install -r scripts/requirements.txt
          inv env.switch prod
          inv tool.install prod

      - name: Publish 🚀
        run: inv publish
